language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
    - node_modules
env:
  - CI=true

jobs:
  include:
    - stage: Tests
      name: Eslint
      script: yarn run lint:js
    - name: Unit Tests
      script: yarn test
    - stage: Deployment
      name: Deploy to AWS Elastic Beanstalk
      before_deploy:
        - yarn build
      deploy:
        provider: elasticbeanstalk
        access_key_id: $ACCESS_KEY_ID
        secret_access_key: $SECRET_ACCESS_KEY
        region: "us-east-2"
        app: "React Testing"
        env: "ReactTesting-env"
        bucket_name: "travis-react-ut"
        on:
          branch: master
